<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use App\Http\Controllers\MailerController;
use DB;

class OTPController extends Controller
{
    // generate new otp
    public function generate_new_otp($email){
        $otp = rand(1000,9999);
        session(['otp' => $otp]);
        session(['email' => $email]);
        session(['expired_at' =>  time()+60*5]);

        return $otp;
    }

    public function compose_mail(Request $request){

        $mailer = new MailerController; 

        // start if register
        if($request->msg_type == 'register'){

            $rules = [
                'email' => ['required','email'],     
            ];

            $validator = Validator::make($request->all(), $rules);

            if($validator->fails()){
                $response = [
                    'status' => 400,
                    'errors' => $validator->messages()
                ];
            }
            else{

                $exist_and_verify = DB::table('accounts')
                    ->where('acc_email', $request->email)
                    ->where('acc_verified_status', '1')
                    ->first();

                if($exist_and_verify){
                    $response = [
                        'status' => 400,
                        'errors' => ['email' => 'The email has already been taken.']
                    ];
                }
                else{
                    $new_otp = $this->generate_new_otp($request->email);
                    $message = 
                    "Hello!,<br>
                    <p>To register your account, Please use this One Time Pin: <b>".$new_otp."</b><br><br>
                    For inquiries or project offers you can reach me at: calmajoseph6@gmail.com<br>
                    <i>***Note: This email is automatically generated by the Nasugbu Online Job Finder. Please do not reply to this email!***</i>";  
                    
                    $send_request = new Request([
                        'email_to' => $request->email,
                        'body' => $message,
                        'subject'  => 'One Time Pin - Nasugbu Online Job Finder'
                    ]);

                    if($mailer->send($send_request)){
                        $response = [
                            'status' => 200,
                            'title' => 'OTP sent!',
                            'message' => 'Check your inbox or “spam” folder.',
                            'icon' => 'success'
                        ];
                    }
                    else{
                        $response = [
                            'status' => 400,
                            'title' => 'OTP not sent!',
                            'message' => 'Something went wrong! Please try again later.',
                            'icon' => 'error'
                        ];
                    }
                }
            }
        }// end if register

        // start if recover
        else{

            $rules = [
                'email' => ['required','exists:accounts,acc_email'],     
            ];

            $messages = [
                'email.exists' => ['The email is not registered.']
            ];

            $validator = Validator::make($request->all(), $rules, $messages);

            if($validator->fails()){
                $response = [
                    'status' => 400,
                    'errors' => $validator->messages()
                ];
            }
            else{
                $new_otp = $this->generate_new_otp($request->email);
                $message = 
                "Hello!,<br>
                <p>To recover your account, Please use this One Time Pin: <b>".$new_otp."</b><br><br>
                For inquiries or project offers you can reach me at: calmajoseph6@gmail.com<br>
                <i>***Note: This email is automatically generated by the Nasugbu Online Job Finder. Please do not reply to this email!***</i>";  
                
                $send_request = new Request([
                    'email_to' => $request->email,
                    'body' => $message,
                    'subject'  => 'One Time Pin - Nasugbu Online Job Finder'
                ]);

                if($mailer->send($send_request)){
                    $response = [
                        'status' => 200,
                        'title' => 'OTP sent!',
                        'message' => 'Check your inbox or “spam” folder.',
                        'icon' => 'success'
                    ];
                }
                else{
                    $response = [
                        'status' => 400,
                        'title' => 'OTP not sent!',
                        'message' => 'Something went wrong! Please try again later.',
                        'icon' => 'error'
                    ];
                } 
            }
            
        }// end if recover
        echo json_encode($response);
    }

    public function verify_otp(Request $request){
        $otp = session('otp');
        $email = session('email');
        $exipired_at = session('expired_at');

        if($otp == $request->otp && $email == $request->email && ($exipired_at >= time())){
            return true;
        }
        else{
            return false;
        }
    }
}
